export const ADD_FILTER_ITEM = 'ADD_FILTER_ITEM';
export const CHECKED_FILTER_ITEM = 'CHECKED_FILTER_ITEM';
export const ADD_TO_CART = 'ADD_TO_CART'; 
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const INCREASE_ITEM = 'INCREASE_ITEM';
export const DECREASE_ITEM = 'DECREASE_ITEM';
export const CLEAR_FILTER_ITEM = 'CLEAR_FILTER_ITEM';

