

let initialState = [
    {
        id: 1,
        img: require('../../img/cart-img1.png'),
        title: 'razer blade 15 studio',
        slogan: 'More Power. More Cores. More Frames.',
        name: 'Razer Blade 15 Studio Edition - OLED 4K Touch 60Hz - Quadro RTX 5000 - Mercury',
        core: 'Intel Core i7-10875H',
        windows: 'Windows 10 Pro',
        display: '15.6" 60Hz OLED 4K Touch',
        card: 'Quadro RTX 5000',
        memory: '32GB RAM, 1TB SSD',
        memoryDetail: '32GB Dual-Channel (16GB x 2) DDR4-2933MHz',
        storage: '1TB SSD (M.2 NVMe PCIe 3.0 x4)', 
        keyboard: 'Per-key RGB powered by Razer Chroma™',
        connectivity: 'Intel® Wireless-AX201 (802.11a/b/g/n/ac/ax), Bluetooth® 5.1',
        input: 'USB 3.2 Gen 2 (USB-A) x 3, USB-C 3.2 Gen 2, Thunderbolt™ 3 (USB-C)',
        audio: 'Built-in Stereo speakers, 3.5mm headphone/microphone combo port, Built-in array microphone, Dolby® Atmos support, 7.1 Codec support (via HDMI)',
        additionalFeatures: 'Razer Synapse 3 enabled with programmable keyboard, Intel® Platform Trust Technology (Intel® PTT) security embedded, Kensington™ Security Slot',
        price: 4299,
        imgDetail1: require('../../img/bg-product-detail1.jpg'),
        imgDetail2: require('../../img/bg-product-detail2.jpg'),
        imgDetail3: require('../../img/bg-product-detail3.jpg'),
        imgDetail4: require('../../img/bg-product-detail4.jpg'),
        imgDetailThumb1: require('../../img/bg-product-detail-thumb1.jpg'),
        imgDetailThumb2: require('../../img/bg-product-detail-thumb2.jpg'),
        imgDetailThumb3: require('../../img/bg-product-detail-thumb3.jpg'),
        imgDetailThumb4: require('../../img/bg-product-detail-thumb4.jpg')
      
    },
    {
        id: 2,
        img: require('../../img/cart-img2.png'),
        title: 'razer blade 15 ',
        slogan: 'Ultra Fast. Ultra Small. Ultra Powerful.',
        name: 'Razer Blade 15 Advanced Edition - Full HD 240Hz - GeForce RTX 2070 Max-Q - Black',
        core: 'Intel Core i7-9750H',
        windows: 'Windows 10 Home',
        display: '15.6" 240Hz Full HD',
        card: 'GeForce RTX 2070',
        memory: '16GB RAM, 512GB SSD',
        memoryDetail: '16GB Dual-Channel (8GB x 2) DDR4 2667MHz',
        storage: '512GB SSD (NVMe)',
        keyboard: 'Per-key RGB powered by Razer Chroma™',
        connectivity: 'Intel® Wireless-AX201 (802.11a/b/g/n/ac/ax), Bluetooth® 5.1',
        input: 'USB 3.2 Gen 2 (USB-A) x 3, USB-C 3.2 Gen 2, Thunderbolt™ 3 (USB-C)',
        audio: 'Built-in Stereo speakers, 3.5mm headphone/microphone combo port, Built-in array microphone, Dolby® Atmos support, 7.1 Codec support (via HDMI)',
        additionalFeatures: 'Razer Synapse 3 enabled with programmable keyboard, Intel® Platform Trust Technology (Intel® PTT) security embedded, Kensington™ Security Slot',
        price: 2599,
        imgDetail1: require('../../img/bg-product-detail21.jpg'),
        imgDetail2: require('../../img/bg-product-detail22.jpg'),
        imgDetail3: require('../../img/bg-product-detail23.jpg'),
        imgDetail4: require('../../img/bg-product-detail24.jpg'),
        imgDetailThumb1: require('../../img/bg-product-detail-thumb21.jpg'),
        imgDetailThumb2: require('../../img/bg-product-detail-thumb22.jpg'),
        imgDetailThumb3: require('../../img/bg-product-detail-thumb23.jpg'),
        imgDetailThumb4: require('../../img/bg-product-detail-thumb24.jpg')
    },
    {
        id: 3,
        img: require('../../img/cart-img3.png'),
        title: 'razer blade 17',
        slogan: 'More Cores. Faster Screen. Bigger Wins.',
        name: 'Razer Blade Pro 17 - Full HD 300Hz - GeForce RTX 2080 Super Max-Q - Black',
        core: 'Intel Core i7-10875H',
        windows: 'Windows 10 Home',
        display: '17.3" 300Hz Full HD',
        card: 'GeForce RTX 2080 Super',
        memory: '16GB RAM, 512GB SSD',
        memoryDetail: '16GB Dual-Channel (8GB x 2) DDR4 2667MHz',
        storage: '512GB SSD (NVMe)',
        keyboard: 'Per-key RGB powered by Razer Chroma™',
        connectivity: 'Intel® Wireless-AX201 (802.11a/b/g/n/ac/ax), Bluetooth® 5.1',
        input: 'USB 3.2 Gen 2 (USB-A) x 3, USB-C 3.2 Gen 2, Thunderbolt™ 3 (USB-C)',
        audio: 'Built-in Stereo speakers, 3.5mm headphone/microphone combo port, Built-in array microphone, Dolby® Atmos support, 7.1 Codec support (via HDMI)',
        additionalFeatures: 'Razer Synapse 3 enabled with programmable keyboard, Intel® Platform Trust Technology (Intel® PTT) security embedded, Kensington™ Security Slot',
        price: 3199,
        imgDetail1: require('../../img/bg-product-detail31.jpg'),
        imgDetail2: require('../../img/bg-product-detail32.jpg'),
        imgDetail3: require('../../img/bg-product-detail33.jpg'),
        imgDetail4: require('../../img/bg-product-detail34.jpg'),
        imgDetailThumb1: require('../../img/bg-product-detail-thumb31.jpg'),
        imgDetailThumb2: require('../../img/bg-product-detail-thumb32.jpg'),
        imgDetailThumb3: require('../../img/bg-product-detail-thumb33.jpg'),
        imgDetailThumb4: require('../../img/bg-product-detail-thumb34.jpg')
    },
    {
        id: 1,
        img: require('../../img/cart-img1.png'),
        title: 'razer blade 15 studio',
        slogan: 'More Power. More Cores. More Frames.',
        name: 'Razer Blade 15 Studio Edition - OLED 4K Touch 60Hz - Quadro RTX 5000 - Mercury',
        core: 'Intel Core i7-10875H',
        windows: 'Windows 10 Pro',
        display: '15.6" 60Hz OLED 4K Touch',
        card: 'Quadro RTX 5000',
        memory: '32GB RAM, 1TB SSD',
        memoryDetail: '32GB Dual-Channel (16GB x 2) DDR4-2933MHz',
        storage: '1TB SSD (M.2 NVMe PCIe 3.0 x4)', 
        keyboard: 'Per-key RGB powered by Razer Chroma™',
        connectivity: 'Intel® Wireless-AX201 (802.11a/b/g/n/ac/ax), Bluetooth® 5.1',
        input: 'USB 3.2 Gen 2 (USB-A) x 3, USB-C 3.2 Gen 2, Thunderbolt™ 3 (USB-C)',
        audio: 'Built-in Stereo speakers, 3.5mm headphone/microphone combo port, Built-in array microphone, Dolby® Atmos support, 7.1 Codec support (via HDMI)',
        additionalFeatures: 'Razer Synapse 3 enabled with programmable keyboard, Intel® Platform Trust Technology (Intel® PTT) security embedded, Kensington™ Security Slot',
        price: 4299,
        imgDetail1: require('../../img/bg-product-detail1.jpg'),
        imgDetail2: require('../../img/bg-product-detail2.jpg'),
        imgDetail3: require('../../img/bg-product-detail3.jpg'),
        imgDetail4: require('../../img/bg-product-detail4.jpg'),
        imgDetailThumb1: require('../../img/bg-product-detail-thumb1.jpg'),
        imgDetailThumb2: require('../../img/bg-product-detail-thumb2.jpg'),
        imgDetailThumb3: require('../../img/bg-product-detail-thumb3.jpg'),
        imgDetailThumb4: require('../../img/bg-product-detail-thumb4.jpg')
      
    },
    {
        id: 2,
        img: require('../../img/cart-img2.png'),
        title: 'razer blade 15 ',
        slogan: 'Ultra Fast. Ultra Small. Ultra Powerful.',
        name: 'Razer Blade 15 Advanced Edition - Full HD 240Hz - GeForce RTX 2070 Max-Q - Black',
        core: 'Intel Core i7-9750H',
        windows: 'Windows 10 Home',
        display: '15.6" 240Hz Full HD',
        card: 'GeForce RTX 2070',
        memory: '16GB RAM, 512GB SSD',
        memoryDetail: '16GB Dual-Channel (8GB x 2) DDR4 2667MHz',
        storage: '512GB SSD (NVMe)',
        keyboard: 'Per-key RGB powered by Razer Chroma™',
        connectivity: 'Intel® Wireless-AX201 (802.11a/b/g/n/ac/ax), Bluetooth® 5.1',
        input: 'USB 3.2 Gen 2 (USB-A) x 3, USB-C 3.2 Gen 2, Thunderbolt™ 3 (USB-C)',
        audio: 'Built-in Stereo speakers, 3.5mm headphone/microphone combo port, Built-in array microphone, Dolby® Atmos support, 7.1 Codec support (via HDMI)',
        additionalFeatures: 'Razer Synapse 3 enabled with programmable keyboard, Intel® Platform Trust Technology (Intel® PTT) security embedded, Kensington™ Security Slot',
        price: 2599,
        imgDetail1: require('../../img/bg-product-detail21.jpg'),
        imgDetail2: require('../../img/bg-product-detail22.jpg'),
        imgDetail3: require('../../img/bg-product-detail23.jpg'),
        imgDetail4: require('../../img/bg-product-detail24.jpg'),
        imgDetailThumb1: require('../../img/bg-product-detail-thumb21.jpg'),
        imgDetailThumb2: require('../../img/bg-product-detail-thumb22.jpg'),
        imgDetailThumb3: require('../../img/bg-product-detail-thumb23.jpg'),
        imgDetailThumb4: require('../../img/bg-product-detail-thumb24.jpg')
    },
    {
        id: 3,
        img: require('../../img/cart-img3.png'),
        title: 'razer blade 17',
        slogan: 'More Cores. Faster Screen. Bigger Wins.',
        name: 'Razer Blade Pro 17 - Full HD 300Hz - GeForce RTX 2080 Super Max-Q - Black',
        core: 'Intel Core i7-10875H',
        windows: 'Windows 10 Home',
        display: '17.3" 300Hz Full HD',
        card: 'GeForce RTX 2080 Super',
        memory: '16GB RAM, 512GB SSD',
        memoryDetail: '16GB Dual-Channel (8GB x 2) DDR4 2667MHz',
        storage: '512GB SSD (NVMe)',
        keyboard: 'Per-key RGB powered by Razer Chroma™',
        connectivity: 'Intel® Wireless-AX201 (802.11a/b/g/n/ac/ax), Bluetooth® 5.1',
        input: 'USB 3.2 Gen 2 (USB-A) x 3, USB-C 3.2 Gen 2, Thunderbolt™ 3 (USB-C)',
        audio: 'Built-in Stereo speakers, 3.5mm headphone/microphone combo port, Built-in array microphone, Dolby® Atmos support, 7.1 Codec support (via HDMI)',
        additionalFeatures: 'Razer Synapse 3 enabled with programmable keyboard, Intel® Platform Trust Technology (Intel® PTT) security embedded, Kensington™ Security Slot',
        price: 3199,
        imgDetail1: require('../../img/bg-product-detail31.jpg'),
        imgDetail2: require('../../img/bg-product-detail32.jpg'),
        imgDetail3: require('../../img/bg-product-detail33.jpg'),
        imgDetail4: require('../../img/bg-product-detail34.jpg'),
        imgDetailThumb1: require('../../img/bg-product-detail-thumb31.jpg'),
        imgDetailThumb2: require('../../img/bg-product-detail-thumb32.jpg'),
        imgDetailThumb3: require('../../img/bg-product-detail-thumb33.jpg'),
        imgDetailThumb4: require('../../img/bg-product-detail-thumb34.jpg')
    }
];

export default function(state=initialState,action){
    switch(action.type){

        default:
            return state;
    }
}